#%RAML 1.0 NamedExample
errorCode: "UNAUTHORIZED"
errorMessage: "No credentials are provided, or the provided credentials are refused."
transactionId: "dd960082-abbf-47c2-8c65-f18eeb35848b"
timeStamp: "2019-09-23T11:46:44.256-05:00"