#%RAML 1.0 NamedExample
errorCode: "METHOD_NOT_SUPPORTED"
errorMessage: "The requested resource does not support the specified HTTP action. Verify that you are calling an action supported by the requested endpoint."
transactionId: "dd960082-abbf-47c2-8c65-f18eeb35848b"
timeStamp: "2019-09-23T11:46:44.256-05:00"