#%RAML 1.0 NamedExample
errorCode: "UNSUPPORTED_MEDIA"
errorMessage: "The server is refusing to service the request because the entity of the request is in a format not supported by the requested resource for the requested method. Verify that Content-Type in your request matches the requested endpoint accepted content."
transactionId: "dd960082-abbf-47c2-8c65-f18eeb35848b"
timeStamp: "2019-09-23T11:46:44.256-05:00"