#%RAML 1.0 NamedExample
errorCode: "INTERNAL_SERVER_ERROR"
errorMessage: "The server encountered an unexpected condition which prevented it from fulfilling the request."
transactionId: "dd960082-abbf-47c2-8c65-f18eeb35848b"
timeStamp: "2019-09-23T11:46:44.256-05:00"