#%RAML 1.0 DataType


type: object
properties:
  case?:
    properties:
      externalId:
        type: string
        required: false
        description: "External System ID"
      id:
        type: string
        required: false
        description: "Case ID"
      isDeleted?:
        type: boolean
        required: false
        description: "Deleted"
      masterRecordId:
        type: string
        required: false
        description: "Master Record ID"
      caseNumber:
        type: string
        required: false
        description: "Case Number"
      contactId:
        type: string
        required: false
        description: "Contact ID"
      accountId:
        type: string
        required: false
        description: "Account ID"
      assetId:
        type: string
        required: false
        description: "Asset ID"
      productId:
        type: string
        required: false
        description: "Product ID"
