#%RAML 1.0 Extension
extends: status.raml # Status RAML API definition to extend
title: salesforce-system-api
description: This is a System API used to interface with various Salesforce objects 
mediaType: application/json
version: v1


uses: 
  common-lib: exchange_modules/02c33166-702d-433f-b25d-8a1b8d871bb2/reusable-raml-fragments/1.0.0/reusable-raml-fragments-library.raml
  


types:
  case: !include data-types/sf-create-case-req-type.raml
 
  

/case:
  type: 
    common-lib.collection:
        example-ref2: !include examples/sf-create-case-req-collection-example.raml
  /{id}:
    type:
      common-lib.collection-item:
        example-ref: !include examples/sf-create-case-req-example.raml
    

      
   

   
   
    
    
   

   
   
  