#%RAML 1.0 NamedExample
[
case:
{
"externalId": "TestName1",
"id": "1234",
"isDeleted": false,
"masterRecordId": "01m805e04566pMs8MNE",
"caseNumber": "2244322"
},
{
"externalId": "TestName1",
"id": "1234",
"isDeleted": false,
"masterRecordId": "01m805e04566pMs8MNE",
"caseNumber": "2244322"
}
]
  