#%RAML 1.0 Trait
#=======================================================================
# Traits/standard-accept-required-trait.raml
# Date   : May 26, 2020
# Author : A. Admassu Psyncopate, Inc.
#=======================================================================
usage: Accept Required Trait

headers:
  Accept:
    type: string
    example: application/json