#%RAML 1.0 Trait
#=======================================================================
# Traits/standard-accept-required-trait.raml
# Date   : May 26, 2020
# Author : A. Admassu Psyncopate, Inc.
#=======================================================================

usage: Client Authorization Required Trait
    
headers:
  Authorization:
    type: string
    example: Bearer QUMxOWM5MDQzNDkzZDRjY2JlYTc2NDdhOTM1ODJmNmFjOTowNjBmNzMyOTc0MTUyOWUzZGMxNmM5NGVjNTNlNWQ0Nw==  