#%RAML 1.0 Trait
#=======================================================================

# Traits/standard-content-type-required-trait.raml
# Date   : May 26, 2020
# Author : A. Admassu Psyncopate, Inc..
#=======================================================================

usage: Content Type Required Trait

headers: 
  Content-Type:
    type: string
    example: application/json