#%RAML 1.0 Trait
#=======================================================================
# Traits/standard-error-responses-trait.raml
# Date   : May 26, 2020
# Author : A. Admassu Psyncopate, Inc.
#=======================================================================

headers:
  x-transaction-id:
    description: Unique transaction ID to provision cross tier traceability.
    required: false
    type: string